name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        required: true
        default: "Hello"
        description: "The greeting to display"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.greeting }}
